-- EXTRA QUESTION
 -- FIND 2ND HIGHEST PRICED PIZZA NAME

SELECT 
    PIZZA_TYPES.NAME, PIZZAS.PRICE
FROM
    PIZZAS
        INNER JOIN
    PIZZA_TYPES ON PIZZAS.PIZZA_TYPE_ID = PIZZA_TYPES.PIZZA_TYPE_ID
ORDER BY (PIZZAS.PRICE) DESC limit 1 offset 2;

