-- QUESTION 12
-- Analyze the cumulative revenue generated over time.
 
sELECT ORDER_DATE , SUM(REVENUE) 
OVER (ORDER BY ORDER_DATE) 
FROM 
 (SELECT ORDERS.ORDER_DATE , 
 SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) AS REVENUE 
 FROM 
 ORDER_DETAILS
 INNER JOIN PIZZAS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID 
 INNER JOIN 
 ORDERS ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDERS_ID
 GROUP BY ORDERS.ORDER_DATE) AS T;
