-- EXTRA QUESTION
-- DETERMINE TOP 2 ORDERED PIZZZA CATEGORY BASED ON REVENUE

SELECT 
    PIZZA_TYPES.CATEGORY,
    ROUND(SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE),
            0) AS REVENUE
FROM
    ORDER_DETAILS
        INNER JOIN
    PIZZAS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
        INNER JOIN
    PIZZA_TYPES ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
GROUP BY PIZZA_TYPES.CATEGORY
ORDER BY REVENUE DESC
LIMIT 2;
