--  QUESTION 
-- Join the necessary tables to find the total quantity of each pizza category ordered. 


SELECT 
PIZZA_TYPES.CATEGORY, SUM(ORDER_DETAILS.QUANTITY)
FROM
ORDER_DETAILS
INNER JOIN
PIZZAS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
JOIN
PIZZA_TYPES ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
GROUP BY PIZZA_TYPES.CATEGORY;
