-- QUESTION 8
-- Join relevant tables to find the category-wise distribution of pizzas.


SELECT 
    PIZZA_TYPES.CATEGORY, SUM(ORDER_DETAILS.QUANTITY)
FROM
    ORDER_DETAILS
        INNER JOIN
    PIZZAS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
        INNER JOIN
    PIZZA_TYPES ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
GROUP BY PIZZA_TYPES.CATEGORY; 
