-- QUESTION 11
-- Calculate the percentage contribution of each pizza type to total revenue.


SELECT 
    PIZZA_TYPES.CATEGORY,
    ROUND((SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) / (SELECT 
                    SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE)
                FROM
                    ORDER_DETAILS
                        INNER JOIN
                    PIZZAS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID)) * 100,
            2) AS PERCENTAGE
FROM
    ORDER_DETAILS
        INNER JOIN
    PIZZAS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
        INNER JOIN
    PIZZA_TYPES ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
GROUP BY PIZZA_TYPES.CATEGORY
ORDER BY PERCENTAGE DESC;
